### ISSUE TITLE
New portal edits  - /register

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#84]
- [ ] Increase padding in the coloured divs - try 36
- [ ] I found a bug with the warnings, but then couldn't replicate (let's double check those when testing)
- [ ] Day dropdown not functional so unable to check Independent

**Comment by cewei8483** [comment]
Day dropdown is enabled after selecting month and year.

**Comment by SKairinos** [comment]
http://development-portal-dot-decent-digit-629.appspot.com/register

**Comment by lauracumming** [comment]
We need to fix the bug that Chris has highlighted please

**Comment by lauracumming** [comment]
@cewei8483 @SKairinos

**Comment by cewei8483** [comment]
@lauracumming @SKairinos  I'm not sure if this is a bug

**Comment by SKairinos** [comment]
@lauracumming @cewei8483 , this is not a bug and is the correct bahviour.  This is actually bug on the original site.

The reason you cannot select day before selecting month and year is we cannot know how many days there until you select the month and year.

For example, January has 31 days but February has 28 days. Furthermore, February has 29 days on a leap year.

Lastly, let's say I originally select 31 Jan, 2023 and then change the month to Feb. Because there is no 31 Feb, 2023 the code will automatically deselect the day and the user will have to select the day again. If the day does exist in the new month, the day will not be deselected.

Hopefully my explanation was clear

**Comment by lauracumming** [comment]
Ah okay, mmm. I think it creates a user experience issue like this. 
I would have thought we could have 31 always and leave it up to the user to choose? @SKairinos

**Comment by lauracumming** [comment]
Here is an example where it is all active: https://www.khanacademy.org/signup

**Comment by lauracumming** [comment]
Would switching it round solve the issue?

**Comment by faucomte97** [comment]
Allow 31 days but then if the overall date is invalid fail form validation with error
